# Generated by Django 4.1.5 on 2023-04-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='batchtype',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='branch',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='batch_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.batchtype'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.level'),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='time_needed',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(),
        ),
    ]
