# Generated by Django 4.1.5 on 2023-04-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_batch_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='topic_batch',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='topic_branch',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
