# Generated by Django 4.1.5 on 2023-04-10 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_topic_order_topic_batch_order_topic_branch_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course_branch'),
        ),
        migrations.AlterField(
            model_name='module_batch',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.module_branch'),
        ),
        migrations.AlterField(
            model_name='subject_batch',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.subject_branch'),
        ),
        migrations.AlterField(
            model_name='topic_batch',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.topic_branch'),
        ),
    ]
