# Generated by Django 4.1.5 on 2023-04-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_batch_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyattendence',
            name='payed_amnt',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
