# Generated by Django 4.1.5 on 2023-04-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_approvals_is_delete_batch_is_delete_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='module',
            name='unique_module_name_per_subject',
        ),
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject_name_per_course',
        ),
        migrations.RemoveConstraint(
            model_name='subtopic',
            name='unique_subtopic_name_per_topic',
        ),
        migrations.RemoveConstraint(
            model_name='topic',
            name='unique_topic_name_per_module',
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
