# Generated by Django 4.1.5 on 2023-04-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_remove_facultyattendence_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module_batch',
            name='clickStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module_batch',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module_branch',
            name='clickStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module_branch',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject_batch',
            name='clickStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject_batch',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject_branch',
            name='clickStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject_branch',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic_batch',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic_branch',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic_batch',
            name='clickStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic_batch',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic_branch',
            name='clickStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic_branch',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
