# Generated by Django 4.1.5 on 2023-04-25 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_module_batch_clickstatus_module_batch_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyattendence',
            name='testimonial',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subtopic_batch',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subtopic'),
        ),
        migrations.AddField(
            model_name='subtopic_batch',
            name='time_needed',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subtopic_branch',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subtopic'),
        ),
        migrations.AddField(
            model_name='subtopic_branch',
            name='time_needed',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
