# Generated by Django 4.1.5 on 2023-04-27 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_facultyattendence_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic_batch',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subtopic_branch'),
        ),
    ]
