# Generated by Django 4.1.5 on 2023-04-29 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0018_alter_subtopic_batch_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facultyattendence',
            name='subtopics_covered',
            field=models.ManyToManyField(blank=True, null=True, to='course.subtopic_batch'),
        ),
    ]
