# Generated by Django 4.1.5 on 2023-04-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_facultyattendence_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_branch',
            name='branch_courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.branch_courses'),
        ),
    ]
