# Generated by Django 4.1.5 on 2023-05-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_approvals_created_at_batch_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_combined',
            field=models.BooleanField(default=False),
        ),
    ]
