# Generated by Django 4.1.5 on 2023-05-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_pricesetting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('date', 'batch')},
        ),
    ]
