# Generated by Django 4.1.5 on 2023-06-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_alter_timetable_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('date', 'batch'), name='unique_timetable_entry'),
        ),
    ]
