# Generated by Django 4.1.5 on 2023-06-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_alter_timetable_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='batch_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.batchtype'),
        ),
    ]
