# Generated by Django 4.1.5 on 2023-06-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_alter_course_batch_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('name',), name='unique_batch_name'),
        ),
        migrations.AddConstraint(
            model_name='branch_courses',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('branch', 'course'), name='unique_branch_course'),
        ),
        migrations.AddConstraint(
            model_name='course_batch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('batch', 'course'), name='unique_batch_course'),
        ),
        migrations.AddConstraint(
            model_name='course_branch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('branch', 'course'), name='unique_course_branch'),
        ),
    ]
