# Generated by Django 4.1.5 on 2023-06-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_batch_unique_batch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyattendence',
            name='salary_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
