# Generated by Django 4.1.5 on 2023-06-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_facultyattendence_salary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyattendence',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
