# Generated by Django 4.1.5 on 2023-06-22 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0032_facultyattendence_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyLimitaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_class', models.IntegerField(null=True)),
                ('current_count', models.IntegerField(null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_limitaion_creator', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='facultylimitaion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('branch', 'faculty'), name='unique_branch_faculty_limitaion'),
        ),
    ]
