# Generated by Django 4.1.5 on 2023-06-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_branch_latitude_branch_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='answer1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
