# Generated by Django 4.1.5 on 2023-06-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0036_review_feedback_alter_review_answer1'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='facultyattendence',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('timetable',), name='unique_timetable_attendance'),
        ),
    ]
