# Generated by Django 4.1.5 on 2023-06-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0037_facultyattendence_unique_timetable_attendance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('date', 'faculty'), name='unique_timetable_entry_faculty'),
        ),
    ]
