# Generated by Django 4.1.5 on 2023-06-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0039_remove_timetable_unique_timetable_entry_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='choice',
            field=models.IntegerField(choices=[(1, 'One star'), (2, 'Two stars'), (3, 'Three stars'), (4, 'Four stars'), (5, 'Five stars')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='on_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.reviewquestions'),
        ),
    ]
