# Generated by Django 4.1.5 on 2023-07-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0040_review_choice_review_on_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='fees',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
