# Generated by Django 4.1.5 on 2023-07-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0043_level_priority_review_is_delete_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('review_on', 'user'), name='unique_rateing_limitaion'),
        ),
    ]
