# Generated by Django 4.1.5 on 2023-07-06 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0044_review_unique_rateing_limitaion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='batch_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.batchtype'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('level', 'batch_type', 'name'), name='unique_course_entry'),
        ),
    ]
