# Generated by Django 4.1.5 on 2023-07-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0045_alter_course_batch_type_course_unique_course_entry'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('name',), name='unique_category_entry'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('category', 'name'), name='unique_level_entry'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('subject', 'name'), name='unique_module_entry'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('course', 'name'), name='unique_subject_entry'),
        ),
        migrations.AddConstraint(
            model_name='subtopic',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('topic', 'name'), name='unique_subtopic_entry'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('module', 'name'), name='unique_topic_entry'),
        ),
    ]
