# Generated by Django 4.1.5 on 2023-07-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0046_category_unique_category_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
