# Generated by Django 4.1.5 on 2023-07-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0047_alter_level_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyattendence',
            name='current_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facultyattendence',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
