# Generated by Django 4.1.5 on 2023-09-28 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_newquestionpool_dtp_edit'),
        ('course', '0054_alter_batch_photo_alter_branch_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltopic',
            name='video',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.studiovideo'),
        ),
        migrations.AddField(
            model_name='topic',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studiovideo'),
        ),
    ]
