# Generated by Django 4.1.5 on 2023-08-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorderpayment',
            name='product',
            field=models.CharField(choices=[('publication', 'publication'), ('subscription', 'subscription'), ('question_paper', 'question paper'), ('exampackages', 'exampackages'), ('videopackages', 'videopackages')], max_length=50),
        ),
    ]
