# Generated by Django 4.1.5 on 2023-09-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_rename_dated_at_historicaltransaction_updated_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bankaccounts',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('acc_no',), name='unique_account_no'),
        ),
    ]
