# Generated by Django 4.1.5 on 2023-09-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_bankaccounts_unique_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccounts',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalbankaccounts',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
