# Generated by Django 4.1.5 on 2023-06-15 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0026_alter_studiocourse_created_by_and_more'),
        ('course', '0032_facultyattendence_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('instruction', models.TextField(null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('postive_mark', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('negative_mark', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('status', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.level')),
                ('question', models.ManyToManyField(to='accounts.question')),
            ],
        ),
        migrations.CreateModel(
            name='DailyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('file', models.FileField(upload_to='')),
                ('video', models.CharField(choices=[('V', 'VIMEO'), ('Y', 'YOUTUBE')], default='V', max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('publish_on', models.DateField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('course', models.ManyToManyField(to='course.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='quizpool',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('level',), name='unique_level_QuizPool'),
        ),
    ]
