# Generated by Django 4.1.5 on 2023-06-26 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MobileApp', '0002_quizpool_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('icon', models.ImageField(upload_to='')),
                ('video', models.CharField(choices=[('V', 'VIMEO'), ('Y', 'YOUTUBE')], default='V', max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('active', models.DateField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
