# Generated by Django 4.1.5 on 2023-06-26 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0003_successstories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successstories',
            name='active',
        ),
    ]
