# Generated by Django 4.1.5 on 2023-06-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0004_remove_successstories_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstories',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
