# Generated by Django 4.1.5 on 2023-06-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0005_successstories_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailynews',
            name='course',
        ),
    ]
