# Generated by Django 4.1.5 on 2023-07-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0006_remove_dailynews_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('width', models.CharField(blank=True, max_length=4, null=True)),
                ('height', models.CharField(blank=True, max_length=4, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
