# Generated by Django 4.1.5 on 2023-07-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0008_mobilebanner_created_at_mobilebanner_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebanner',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
