# Generated by Django 4.1.5 on 2023-07-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0044_review_unique_rateing_limitaion'),
        ('student', '0021_publications_is_online_publications_medium_and_more'),
        ('MobileApp', '0010_studymaterial_questionbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.batch')),
                ('publications', models.ManyToManyField(blank=True, to='student.publications')),
                ('question_book', models.ManyToManyField(blank=True, to='MobileApp.questionbook')),
                ('study_meterial', models.ManyToManyField(blank=True, to='MobileApp.studymaterial')),
            ],
        ),
    ]
