# Generated by Django 4.1.5 on 2023-07-07 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0046_category_unique_category_entry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MobileApp', '0011_batchpackages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.URLField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.level')),
            ],
        ),
        migrations.AddField(
            model_name='questionbook',
            name='admission_time_price',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='questionbook',
            name='old_student',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='questionbook',
            name='outsider',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='admission_time_price',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='old_student',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='outsider',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='ShortsWatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('shorts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileApp.shorts')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
