# Generated by Django 4.1.5 on 2023-07-07 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_publications_admission_time_price_and_more'),
        ('course', '0046_category_unique_category_entry_and_more'),
        ('MobileApp', '0012_shorts_questionbook_admission_time_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.branch')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.publications')),
                ('questionbank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MobileApp.questionbook')),
                ('studymaterial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MobileApp.studymaterial')),
            ],
        ),
        migrations.AddField(
            model_name='questionbook',
            name='q_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MobileApp.questioncategory'),
        ),
    ]
