# Generated by Django 4.1.5 on 2023-07-12 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0048_alter_facultyattendence_current_salary_and_more'),
        ('MobileApp', '0015_quizpooluserroom_quizpoolanswers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='mobilebanner',
            name='banner_assign',
            field=models.CharField(choices=[('TR', 'TRENDING'), ('V', 'VIDEO'), ('P', 'PDF'), ('A', 'AUDIO'), ('C', 'COURSE'), ('PU', 'PUBLICATION'), ('TI', 'TICKET'), ('E', 'EXAM'), ('TH', 'TALENT HUNT'), ('EL', 'EXTERNAL LINK')], default='TR', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stock', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('purchased_on', models.DateField(null=True)),
                ('subscription_upto', models.DateField(null=True)),
                ('is_lend', models.BooleanField(default=True)),
                ('qrcode', models.CharField(max_length=255, null=True, unique=True)),
                ('ISBN', models.CharField(max_length=100, null=True)),
                ('outsider_allowed', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.branch')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileApp.bookstype')),
            ],
        ),
    ]
