# Generated by Django 4.1.5 on 2023-07-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0016_bookstype_mobilebanner_banner_assign_books'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='batchpackages',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('batch',), name='unique_batch_BatchPackages'),
        ),
    ]
