# Generated by Django 4.1.5 on 2023-07-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0019_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='publication',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
