# Generated by Django 4.1.5 on 2023-07-15 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0024_publications_offlinebook_price'),
        ('MobileApp', '0021_rename_stock_books_no_due_days_books_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountpaid', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('batch_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileApp.batchpackages')),
                ('publications', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.publications')),
                ('question_banks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MobileApp.questionbook')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('study_materials', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MobileApp.studymaterial')),
            ],
        ),
    ]
