# Generated by Django 4.1.5 on 2023-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_publications_offlinebook_price'),
        ('MobileApp', '0022_studentfeecollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeecollection',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='studentfeecollection',
            name='question_banks',
        ),
        migrations.RemoveField(
            model_name='studentfeecollection',
            name='study_materials',
        ),
        migrations.AddField(
            model_name='studentfeecollection',
            name='publications',
            field=models.ManyToManyField(null=True, to='student.publications'),
        ),
        migrations.AddField(
            model_name='studentfeecollection',
            name='question_banks',
            field=models.ManyToManyField(null=True, to='MobileApp.questionbook'),
        ),
        migrations.AddField(
            model_name='studentfeecollection',
            name='study_materials',
            field=models.ManyToManyField(null=True, to='MobileApp.studymaterial'),
        ),
    ]
