# Generated by Django 4.1.5 on 2023-07-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_publications_offlinebook_price'),
        ('MobileApp', '0023_remove_studentfeecollection_publications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeecollection',
            name='publications',
            field=models.ManyToManyField(blank=True, to='student.publications'),
        ),
        migrations.AlterField(
            model_name='studentfeecollection',
            name='question_banks',
            field=models.ManyToManyField(blank=True, to='MobileApp.questionbook'),
        ),
        migrations.AlterField(
            model_name='studentfeecollection',
            name='study_materials',
            field=models.ManyToManyField(blank=True, to='MobileApp.studymaterial'),
        ),
    ]
