# Generated by Django 4.1.5 on 2023-07-19 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_incentives_staffsalary_staffincentives_and_more'),
        ('course', '0048_alter_facultyattendence_current_salary_and_more'),
        ('MobileApp', '0024_alter_studentfeecollection_publications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.level')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studiovideo')),
            ],
        ),
    ]
