# Generated by Django 4.1.5 on 2023-07-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_remove_incentives_target_and_more'),
        ('MobileApp', '0027_remove_quizpool_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpool',
            name='question',
            field=models.ManyToManyField(to='accounts.newquestionpool'),
        ),
    ]
