# Generated by Django 4.1.5 on 2023-07-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_remove_incentives_target_and_more'),
        ('MobileApp', '0029_remove_quizpoolanswers_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpoolanswers',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.newquestionpool'),
        ),
        migrations.AlterField(
            model_name='quizpool',
            name='question',
            field=models.ManyToManyField(to='accounts.newquestionpool'),
        ),
    ]
