# Generated by Django 4.1.5 on 2023-07-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0030_quizpoolanswers_question_alter_quizpool_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuser',
            name='dues_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
