# Generated by Django 4.1.5 on 2023-07-22 10:04

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0043_incentives_types'),
        ('MobileApp', '0033_stories_storiescategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('file', models.FileField(storage=accounts.models.S3Storage(), upload_to='materials/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx', 'docx', 'plg', 'png', 'jpeg'])])),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VedioMeterialAndQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ManyToManyField(blank=True, to='MobileApp.packagematerials')),
                ('questionpaper', models.ManyToManyField(blank=True, to='accounts.questionpaper')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studiovideo')),
            ],
        ),
        migrations.CreateModel(
            name='VedioPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('premium', models.BooleanField(default=False)),
                ('videos', models.ManyToManyField(to='MobileApp.vediometerialandquestions')),
            ],
        ),
    ]
