# Generated by Django 4.1.5 on 2023-07-24 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0035_comments_comment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comments',
            name='unique_comment_assign_constraints',
        ),
    ]
