# Generated by Django 4.1.5 on 2023-07-25 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0037_comments_created_at_likes_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpoolanswers',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='quizpoolanswers',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='quizpoolanswers',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('room', 'index'), name='room_index_quiz_answer_submit'),
        ),
        migrations.AddConstraint(
            model_name='quizpoolanswers',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('room', 'question'), name='room_question_quiz_answer_submit'),
        ),
    ]
