# Generated by Django 4.1.5 on 2023-07-25 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MobileApp', '0039_storiescategory_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like_assign',
            field=models.CharField(choices=[('SHORTS', 'SHORTS'), ('CURRENT_AFFAIRS', 'CURRENT AFFAIRS'), ('STUDY_MATERIALS', 'STUDY MATERIALS'), ('QUESTION_PAPER', 'QUESTION PAPER'), ('VIDEOS', 'VIDEOS'), ('COMMENTS', 'COMMENTS'), ('STORIES', 'STORIES')], default='S', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='CurrentAffairsQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('postive_mark', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('negative_mark', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration', models.IntegerField(null=True)),
                ('question_text', models.TextField(null=True)),
                ('option_1', models.TextField()),
                ('option_2', models.TextField()),
                ('option_3', models.TextField()),
                ('option_4', models.TextField()),
                ('option_5', models.TextField(blank=True, null=True)),
                ('answer', models.CharField(choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3'), ('option_4', 'Option 4'), ('option_5', 'Option 5')], max_length=255, null=True)),
                ('answerhint', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('1', 'Medium'), ('2', 'Simple'), ('3', 'Tough'), ('4', 'All')], max_length=1, null=True)),
                ('status', models.BooleanField(default=True)),
                ('publish', models.BooleanField(default=False, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='currentaffairsquestions',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('user', 'question_text', 'option_1', 'option_2', 'option_3', 'option_4', 'answer'), name='unique_question_answers'),
        ),
    ]
