# Generated by Django 4.1.5 on 2023-07-25 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0048_alter_facultyattendence_current_salary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0043_incentives_types'),
        ('MobileApp', '0040_alter_likes_like_assign_currentaffairsquestions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampaperPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('imagetitle', models.CharField(max_length=255, null=True)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('premium', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exampaper', models.ManyToManyField(to='accounts.questionpaper')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.level')),
            ],
        ),
    ]
