# Generated by Django 4.1.5 on 2023-07-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0041_exampaperpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAffairsVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('published', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('publish_on', models.DateField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='currentaffairsquestions',
            name='publish_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='currentaffairsquestions',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
