# Generated by Django 4.1.5 on 2023-07-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0042_currentaffairsvideos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentaffairsquestions',
            name='publish',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_assign',
            field=models.CharField(choices=[('SHORTS', 'SHORTS'), ('CURRENT_AFFAIRS', 'CURRENT AFFAIRS'), ('STUDY_MATERIALS', 'STUDY MATERIALS'), ('QUESTION_PAPER', 'QUESTION PAPER'), ('VIDEOS', 'VIDEOS'), ('COMMENTS', 'COMMENTS'), ('STORIES', 'STORIES')], default='SHORTS', max_length=200, null=True),
        ),
    ]
