# Generated by Django 4.1.5 on 2023-07-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0043_remove_currentaffairsquestions_publish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentaffairsquestions',
            name='answerhint',
        ),
        migrations.RemoveField(
            model_name='currentaffairsquestions',
            name='type',
        ),
    ]
