# Generated by Django 4.1.5 on 2023-07-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0044_remove_currentaffairsquestions_answerhint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vediometerialandquestions',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
