# Generated by Django 4.1.5 on 2023-08-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0050_generalvideosmaterial_remove_generalvideos_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalvideos',
            name='thumbnails',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
