# Generated by Django 4.1.5 on 2023-08-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0054_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilebanner',
            name='banner_assign',
        ),
        migrations.AddField(
            model_name='dailyexams',
            name='banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='exampaperpackage',
            name='banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mobilebanner',
            name='route',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mobilebanner',
            name='subroutes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='previousexams',
            name='banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='specialexams',
            name='banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='storiescategory',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vediopackage',
            name='banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
