# Generated by Django 4.1.5 on 2023-08-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0055_remove_mobilebanner_banner_assign_dailyexams_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexams',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exampaperpackage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='previousexams',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='specialexams',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vediopackage',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
