# Generated by Django 4.1.5 on 2023-08-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0056_dailyexams_description_exampaperpackage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalvideos',
            name='files',
        ),
    ]
