# Generated by Django 4.1.5 on 2023-08-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0057_remove_generalvideos_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalvideos',
            name='files',
            field=models.ManyToManyField(blank=True, to='MobileApp.generalvideosmaterial'),
        ),
    ]
