# Generated by Django 4.1.5 on 2023-08-04 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_materialreference_only_one_field_non_null_constraint'),
        ('MobileApp', '0058_generalvideos_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='vediometerialandquestions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vediometerialandquestions',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studiovideo'),
        ),
        migrations.AlterField(
            model_name='vediopackage',
            name='videos',
            field=models.ManyToManyField(blank=True, to='MobileApp.vediometerialandquestions'),
        ),
    ]
