# Generated by Django 4.1.5 on 2023-08-08 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_materialreference_only_one_field_non_null_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MobileApp', '0060_scholarshiptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stories',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PollFightQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('points', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField(default=False)),
                ('question', models.ManyToManyField(blank=True, to='accounts.newquestionpool')),
            ],
        ),
        migrations.CreateModel(
            name='PollFightLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=True)),
                ('user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_1_lobby', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_2_lobby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
