# Generated by Django 4.1.5 on 2023-08-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0061_stories_active_stories_created_by_pollfightquestion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='popularfaculty',
            name='unique_faculty_course',
        ),
        migrations.AddConstraint(
            model_name='popularfaculty',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('faculty', 'course', 'priority'), name='unique_faculty_course'),
        ),
    ]
