# Generated by Django 4.1.5 on 2023-08-10 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0062_remove_popularfaculty_unique_faculty_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshiptype',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storiescategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='storiescategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
