# Generated by Django 4.1.5 on 2023-08-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0065_popularfaculty_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pollfightlobby',
            name='unique_poll-users',
        ),
        migrations.AddField(
            model_name='scholarshipapproval',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarshipapproval',
            name='description_approv_reject',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapproval',
            name='description_request',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapproval',
            name='reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_assign',
            field=models.CharField(choices=[('SHORTS', 'SHORTS'), ('CURRENT_AFFAIRS', 'CURRENT AFFAIRS'), ('STUDY_MATERIALS', 'STUDY MATERIALS'), ('QUESTION_PAPER', 'QUESTION PAPER'), ('VIDEOS', 'VIDEOS'), ('COMMENTS', 'COMMENTS'), ('STORIES', 'STORIES'), ('SUCCESS_STORIES', 'SUCCESS_STORIES')], default='SHORTS', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='likes',
            name='like_assign',
            field=models.CharField(choices=[('SHORTS', 'SHORTS'), ('CURRENT_AFFAIRS', 'CURRENT AFFAIRS'), ('STUDY_MATERIALS', 'STUDY MATERIALS'), ('QUESTION_PAPER', 'QUESTION PAPER'), ('VIDEOS', 'VIDEOS'), ('COMMENTS', 'COMMENTS'), ('STORIES', 'STORIES'), ('SUCCESS_STORIES', 'SUCCESS STORIES')], default='S', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='views',
            name='view_assign',
            field=models.CharField(choices=[('SHORTS', 'SHORTS'), ('CURRENT_AFFAIRS', 'CURRENT AFFAIRS'), ('STUDY_MATERIALS', 'STUDY MATERIALS'), ('QUESTION_PAPER', 'QUESTION PAPER'), ('VIDEOS', 'VIDEOS'), ('COMMENTS', 'COMMENTS'), ('STORIES', 'STORIES'), ('SUCCESS_STORIES', 'SUCCESS STORIES')], default='S', max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='pollfightlobby',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_poll_users'),
        ),
    ]
