# Generated by Django 4.1.5 on 2023-08-11 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MobileApp', '0066_remove_pollfightlobby_unique_poll-users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapproval',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
