# Generated by Django 4.1.5 on 2023-08-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0067_alter_scholarshipapproval_approved_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pollfightlobby',
            name='unique_poll_users',
        ),
        migrations.AddConstraint(
            model_name='pollfightlobby',
            constraint=models.CheckConstraint(check=models.Q(('user1__isnull', True), ('user2__isnull', True), models.Q(('user1', models.F('user2')), _negated=True), _connector='OR'), name='user1_user2_not_same_constraint'),
        ),
    ]
