# Generated by Django 4.1.5 on 2023-08-12 07:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_materialuploads_updated_at_and_more'),
        ('MobileApp', '0068_remove_pollfightlobby_unique_poll_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollFightSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_copy', models.TextField()),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('option_5', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.CharField(choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3'), ('option_4', 'Option 4'), ('option_5', 'Option 5')], max_length=255, null=True)),
                ('crct_answer', models.CharField(choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3'), ('option_4', 'Option 4'), ('option_5', 'Option 5')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('index', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.newquestionpool')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileApp.pollfightlobby')),
            ],
        ),
    ]
