# Generated by Django 4.1.5 on 2023-08-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0050_historicalcourse'),
        ('MobileApp', '0071_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='vediopackage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.category'),
        ),
        migrations.AddField(
            model_name='vediopackage',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.level'),
        ),
    ]
