# Generated by Django 4.1.5 on 2023-09-01 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MobileApp', '0073_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='option_4',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='option_5',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='question',
        ),
        migrations.CreateModel(
            name='GroupMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('option_1', models.CharField(blank=True, max_length=255, null=True)),
                ('option_2', models.CharField(blank=True, max_length=255, null=True)),
                ('option_3', models.CharField(blank=True, max_length=255, null=True)),
                ('option_4', models.CharField(blank=True, max_length=255, null=True)),
                ('option_5', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.CharField(blank=True, choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3'), ('option_4', 'Option 4'), ('option_5', 'Option 5')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MobileApp.groups')),
                ('mcq', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MobileApp.groupmcq')),
                ('post', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MobileApp.posts')),
            ],
        ),
    ]
