# Generated by Django 4.1.5 on 2023-09-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0074_remove_posts_answer_remove_posts_option_1_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupmcq',
            constraint=models.CheckConstraint(check=models.Q(('question__isnull', False), ('option_1__isnull', False), ('option_2__isnull', False)), name='question-chat-required'),
        ),
        migrations.AddConstraint(
            model_name='posts',
            constraint=models.CheckConstraint(check=models.Q(('message__isnull', False)), name='posts-chat-required'),
        ),
    ]
