# Generated by Django 4.1.5 on 2023-09-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0075_groupmcq_question-chat-required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmcq',
            name='option_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groupmcq',
            name='option_2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groupmcq',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='message',
            field=models.TextField(),
        ),
    ]
