# Generated by Django 4.1.5 on 2023-09-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0076_alter_groupmcq_option_1_alter_groupmcq_option_2_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupchat',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('post__isnull', True), ('mcq__isnull', False)), models.Q(('post__isnull', False), ('mcq__isnull', True)), _connector='OR'), name='question-chat-required-or-mcq'),
        ),
    ]
