# Generated by Django 4.1.5 on 2023-09-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0077_groupchat_question-chat-required-or-mcq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='group',
        ),
        migrations.AddConstraint(
            model_name='groupchat',
            constraint=models.CheckConstraint(check=models.Q(('group__isnull', False)), name='group-chat-required-group'),
        ),
    ]
