# Generated by Django 4.1.5 on 2023-09-02 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MobileApp', '0078_remove_posts_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollfightlobby',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_lobby', to=settings.AUTH_USER_MODEL),
        ),
    ]
