# Generated by Django 4.1.5 on 2023-09-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0079_pollfightlobby_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorts',
            name='video_file',
            field=models.FileField(upload_to='shorts/'),
        ),
    ]
