# Generated by Django 4.1.5 on 2023-09-04 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MobileApp', '0080_alter_shorts_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('purchase_item', models.CharField(choices=[('EXAM_PACKAGE', 'EXAM_PACKAGE'), ('PUBLICATION', 'PUBLICATION'), ('STUDY_MATERIALS', 'STUDY MATERIALS'), ('QUESTION_PAPER', 'QUESTION PAPER'), ('VIDEO_PACKAGE', 'VIDEO_PACKAGE'), ('COURSE_PURCHASE', 'COURSE_PURCHASE')], max_length=200)),
                ('purchase_item_id', models.BigIntegerField()),
                ('purchase_amount', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseDetails',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('purchase_item', models.CharField(choices=[('EXAM_PACKAGE', 'EXAM_PACKAGE'), ('PUBLICATION', 'PUBLICATION'), ('STUDY_MATERIALS', 'STUDY MATERIALS'), ('QUESTION_PAPER', 'QUESTION PAPER'), ('VIDEO_PACKAGE', 'VIDEO_PACKAGE'), ('COURSE_PURCHASE', 'COURSE_PURCHASE')], max_length=200)),
                ('purchase_item_id', models.BigIntegerField()),
                ('purchase_amount', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical purchase details',
                'verbose_name_plural': 'historical purchase detailss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
