# Generated by Django 4.1.5 on 2023-09-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0082_groups_category_groups_course_groups_level_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groups',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('category__isnull', False), ('level__isnull', True), ('course__isnull', True)), models.Q(('category__isnull', True), ('level__isnull', False), ('course__isnull', True)), models.Q(('category__isnull', True), ('level__isnull', True), ('course__isnull', False)), _connector='OR'), name='only_one_field_non_null_constraint_for_group'),
        ),
    ]
