# Generated by Django 4.1.5 on 2023-09-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0083_groups_only_one_field_non_null_constraint_for_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='vediometerialandquestions',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
