# Generated by Django 4.1.5 on 2023-09-11 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0052_historicaltopic_historicalsubtopic_historicalsubject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0056_studiovideo_thumbnail'),
        ('MobileApp', '0084_vediometerialandquestions_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageQuizPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('instruction', models.TextField(null=True)),
                ('duration', models.IntegerField(default=5)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('postive_mark', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('negative_mark', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('status', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.level')),
                ('question', models.ManyToManyField(to='accounts.newquestionpool')),
            ],
        ),
        migrations.AddField(
            model_name='vediopackage',
            name='question_paper_attempt_limit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='PackageQuizPoolUserRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('is_status', models.BooleanField(default=True)),
                ('is_submited', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileApp.packagequizpool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageQuizPoolAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_copy', models.TextField()),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('option_5', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.CharField(choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3'), ('option_4', 'Option 4'), ('option_5', 'Option 5')], max_length=255, null=True)),
                ('crct_answer', models.CharField(choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3'), ('option_4', 'Option 4'), ('option_5', 'Option 5')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('index', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.newquestionpool')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileApp.packagequizpooluserroom')),
            ],
        ),
    ]
