# Generated by Django 4.1.5 on 2023-09-12 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0058_faculty_is_delete_historicalfaculty_is_delete'),
        ('MobileApp', '0088_studentfeecollection_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionpaperAttend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('exampackage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MobileApp.exampaperpackage')),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.questionpaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videopackage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MobileApp.vediopackage')),
            ],
        ),
    ]
