# Generated by Django 4.1.5 on 2023-09-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0091_exampaperpackage_attend_count'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pollfightsubmit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('room', 'index', 'created_by'), name='unique_quiz_submit_for_user'),
        ),
    ]
