# Generated by Django 4.1.5 on 2023-09-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0092_pollfightsubmit_unique_quiz_submit_for_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebanner',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
