# Generated by Django 4.1.5 on 2023-09-15 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0096_bookstock_created_at_bookstock_omr_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='community/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='posts',
            name='posts-chat-required',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='message',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='posts',
            constraint=models.CheckConstraint(check=models.Q(('title__isnull', False)), name='posts-chat-required'),
        ),
        migrations.AddField(
            model_name='posts',
            name='images',
            field=models.ManyToManyField(blank=True, to='MobileApp.communityimage'),
        ),
    ]
