# Generated by Django 4.1.5 on 2023-09-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0098_examcategory_examquestionpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestionpaper',
            name='is_qr',
            field=models.BooleanField(default=False),
        ),
    ]
