# Generated by Django 4.1.5 on 2023-09-22 06:08

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0054_alter_batch_photo_alter_branch_photo_and_more'),
        ('MobileApp', '0101_alter_currentaffairsvideosassign_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebanner',
            name='image',
            field=models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='dev-aceapp-public', default_acl='public-read', querystring_auth=False), upload_to='Images/'),
        ),
        migrations.CreateModel(
            name='OnlineCoursePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('descriptions', models.TextField()),
                ('validity', models.DurationField()),
                ('benifites', models.TextField()),
                ('prize', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('strike_prize', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_type', models.CharField(choices=[('fullpayment', 'fullpayment'), ('installment', 'installment')], default='fullpayment', max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
