# Generated by Django 4.1.5 on 2023-09-29 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0065_newquestionpool_dtp_edit'),
        ('MobileApp', '0107_historicallibraryfine_book_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalonlinecoursepackage',
            name='validity',
        ),
        migrations.RemoveField(
            model_name='onlinecoursepackage',
            name='validity',
        ),
        migrations.AlterField(
            model_name='examquestionpaper',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.CreateModel(
            name='OfflineExamQuizPoolUserRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('count', models.IntegerField(null=True)),
                ('is_status', models.BooleanField(default=True)),
                ('is_submited', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('question_paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MobileApp.examquestionpaper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineExamQuizPoolAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_copy', models.TextField()),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('option_5', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.CharField(choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3'), ('option_4', 'Option 4'), ('option_5', 'Option 5')], max_length=255, null=True)),
                ('crct_answer', models.CharField(choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3'), ('option_4', 'Option 4'), ('option_5', 'Option 5')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('index', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.newquestionpool')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileApp.offlineexamquizpooluserroom')),
            ],
        ),
    ]
