# Generated by Django 4.1.5 on 2023-09-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0108_remove_historicalonlinecoursepackage_validity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalonlinecoursepackage',
            name='validity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onlinecoursepackage',
            name='validity',
            field=models.IntegerField(default=0),
        ),
    ]
