# Generated by Django 4.1.5 on 2023-03-31 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='expected_salary',
        ),
    ]
