# Generated by Django 4.1.5 on 2023-04-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_faculty_expected_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_salary',
            old_name='salary',
            new_name='exp_salary',
        ),
        migrations.AddField(
            model_name='faculty_salary',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        )
    ]
