# Generated by Django 4.1.5 on 2023-04-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_salary_faculty_salary_exp_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_salary',
            name='fixed_salary',
        ),
    ]
