# Generated by Django 4.1.5 on 2023-04-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_faculty_salary_fixed_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_salary',
            name='fixed_salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.salaryfixation'),
        ),
    ]
