# Generated by Django 4.1.5 on 2023-04-17 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_reviewquestions_rating_rate_fac_specialholiday_and_more'),
        ('accounts', '0006_faculty_salary_fixed_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpool',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[(models.CharField(max_length=255), 'Option 1'), (models.CharField(max_length=255), 'Option 2'), (models.CharField(max_length=255), 'Option 3'), (models.CharField(max_length=255), 'Option 4'), (models.CharField(blank=True, max_length=255, null=True), 'Option 5')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionpool',
            name='type',
            field=models.CharField(choices=[('1', 'Practise test'), ('2', 'Question Paper')], max_length=1),
        ),
    ]
