# Generated by Django 4.1.5 on 2023-04-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_questionpool_subject_alter_question_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3'), ('option_4', 'Option 4'), ('option_5', 'Option 5')], max_length=255, null=True),
        ),
    ]
