# Generated by Django 4.1.5 on 2023-04-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_experience_is_delete_faculty_salary_is_delete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
