# Generated by Django 4.1.5 on 2023-04-27 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_facultyattendence_testimonial_and_more'),
        ('accounts', '0010_questionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewQuestionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(null=True)),
                ('option_1', models.CharField(default='', max_length=255)),
                ('option_2', models.CharField(default='', max_length=255)),
                ('option_3', models.CharField(default='', max_length=255)),
                ('option_4', models.CharField(default='', max_length=255)),
                ('option_5', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.CharField(choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3'), ('option_4', 'Option 4'), ('option_5', 'Option 5')], max_length=255, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('1', 'Practise test'), ('2', 'Question Paper')], max_length=1)),
                ('status', models.BooleanField(default=False)),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('levels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.topic')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('1', 'Practise test'), ('2', 'Question Paper')], max_length=1)),
                ('status', models.BooleanField(default=False)),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.category')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('levels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.level')),
                ('questions', models.ManyToManyField(to='accounts.newquestionpool')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subject')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
