# Generated by Django 4.1.5 on 2023-04-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_newquestionpool_questionpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newquestionpool',
            name='option_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newquestionpool',
            name='option_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newquestionpool',
            name='option_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newquestionpool',
            name='option_4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newquestionpool',
            name='option_5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
