# Generated by Django 4.1.5 on 2023-05-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_newquestionpool_option_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyfile', models.ImageField(upload_to='')),
            ],
        ),
    ]
