# Generated by Django 4.1.5 on 2023-05-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_questionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfile',
            name='facultyfile',
            field=models.FileField(upload_to=''),
        ),
    ]
