# Generated by Django 4.1.5 on 2023-05-18 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_facultyattendence_current_salary_and_more'),
        ('accounts', '0015_declaration_created_at_experience_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=122)),
                ('publish', models.BooleanField(default=False)),
                ('assignvideo', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_studio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudioNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('district', models.CharField(max_length=225)),
                ('address', models.TextField()),
                ('phonenumber', models.IntegerField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='declaration',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='newquestionpool',
            name='publish',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.category'),
        ),
        migrations.AlterField(
            model_name='material',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='material',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty'),
        ),
        migrations.AlterField(
            model_name='material',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.level'),
        ),
        migrations.AlterField(
            model_name='material',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subject'),
        ),
        migrations.CreateModel(
            name='StudioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('shootingdaytime', models.DateTimeField()),
                ('shootingenddaytime', models.DateTimeField()),
                ('editingdaytime', models.DateTimeField()),
                ('editingenddaytime', models.DateTimeField()),
                ('videolink', models.TextField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('editingstaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudioCourseAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.module')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subject')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subtopic')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.topic')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studiocourse')),
            ],
        ),
        migrations.AddField(
            model_name='studiocourse',
            name='studioname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studionames'),
        ),
        migrations.AddField(
            model_name='studiocourse',
            name='topic',
            field=models.ManyToManyField(to='course.topic'),
        ),
        migrations.AddField(
            model_name='studiocourse',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studiovideo'),
        ),
        migrations.CreateModel(
            name='FacultyStudioApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('videourl', models.URLField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('studiocourse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studiocourse')),
            ],
        ),
    ]
