# Generated by Django 4.1.5 on 2023-05-22 11:13

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_studiocourse_studionames_declaration_is_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(storage=accounts.models.S3Storage(), upload_to='materials/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx', 'docx', 'plg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='studionames',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
