# Generated by Django 4.1.5 on 2023-05-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_material_updated_at_user_is_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialUploadSupport',
        ),
    ]
