# Generated by Django 4.1.5 on 2023-05-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_pricesetting'),
        ('accounts', '0018_delete_materialuploadsupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='idverified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='photoverified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='resumeverified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopic', to='course.subtopic'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='examtype',
            field=models.CharField(choices=[('1', 'Course'), ('2', 'Subject'), ('3', 'Module'), ('4', 'Topic'), ('5', 'Model')], max_length=1, null=True),
        ),
    ]
