# Generated by Django 4.1.5 on 2023-05-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_pricesetting'),
        ('accounts', '0019_faculty_idverified_faculty_photoverified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='subtopic',
        ),
        migrations.AddField(
            model_name='material',
            name='subtopic',
            field=models.ManyToManyField(blank=True, to='course.subtopic'),
        ),
    ]
