# Generated by Django 4.1.5 on 2023-06-06 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_material_subtopic_material_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiovideo',
            name='adminverify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studiovideo',
            name='existing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studiovideo',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_studio_video', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studiovideo',
            name='video_length',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studiovideo',
            name='videocontent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studiovideo',
            name='vimeoid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studiocourseassign',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studiovideo'),
        ),
        migrations.AlterField(
            model_name='studiovideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studiovideo',
            name='editingdaytime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studiovideo',
            name='editingenddaytime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studiovideo',
            name='editingstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studiovideo',
            name='shootingdaytime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studiovideo',
            name='shootingenddaytime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studiovideo',
            name='videolink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
