# Generated by Django 4.1.5 on 2023-06-14 05:58

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_facultyattendence_salary_date'),
        ('accounts', '0024_faculty_otp_facultycourseaddition_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('file', models.FileField(storage=accounts.models.S3Storage(), upload_to='materials/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx', 'docx', 'plg', 'png', 'jpeg'])])),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('batch', models.ManyToManyField(to='course.batch')),
                ('course', models.ManyToManyField(to='course.course')),
                ('uploads', models.ManyToManyField(to='accounts.materialreference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
