# Generated by Django 4.1.5 on 2023-06-14 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_convertedmaterials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiocourse',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studiocourse',
            name='studioname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studionames'),
        ),
    ]
