# Generated by Django 4.1.5 on 2023-06-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_studiocourse_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialuploads',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
