# Generated by Django 4.1.5 on 2023-06-20 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_facultyattendence_status'),
        ('accounts', '0027_materialuploads_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedmaterials',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='convertedmaterials',
            name='topic',
            field=models.ManyToManyField(blank=True, to='course.topic'),
        ),
        migrations.AlterField(
            model_name='convertedmaterials',
            name='batch',
            field=models.ManyToManyField(blank=True, to='course.batch'),
        ),
        migrations.AlterField(
            model_name='convertedmaterials',
            name='course',
            field=models.ManyToManyField(blank=True, to='course.course'),
        ),
    ]
