# Generated by Django 4.1.5 on 2023-06-23 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_facultylimitaion_and_more'),
        ('accounts', '0028_convertedmaterials_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('like', models.BooleanField()),
                ('dislike', models.BooleanField()),
                ('is_delete', models.BooleanField(default=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.convertedmaterials')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.timetable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
