# Generated by Django 4.1.5 on 2023-06-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_materialrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_salary',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faculty_salary',
            name='exp_salary',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
