# Generated by Django 4.1.5 on 2023-07-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_convertedmaterials_batch_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='facultycourseaddition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('user', 'topic'), name='unique_faculty_topic'),
        ),
    ]
