# Generated by Django 4.1.5 on 2023-07-04 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0041_batch_fees_batch_is_special'),
        ('accounts', '0034_facultycourseaddition_unique_faculty_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='newquestionpool',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subtopic'),
        ),
    ]
