# Generated by Django 4.1.5 on 2023-07-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_newquestionpool_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='newquestionpool',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='newquestionpool',
            name='negative_mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='newquestionpool',
            name='postive_mark',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
