# Generated by Django 4.1.5 on 2023-07-04 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_newquestionpool_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrating',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CommentOnMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True, null=True)),
                ('comment_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.convertedmaterials')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
