# Generated by Django 4.1.5 on 2023-07-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_materialrating_feedback_commentonmaterial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='newquestionpool',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('user', 'subtopic', 'question_text', 'option_1', 'option_2', 'option_3', 'option_4'), name='unique_sub_topic_question'),
        ),
    ]
