# Generated by Django 4.1.5 on 2023-07-17 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_faculty_salary_exp_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('target', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('conditions', models.TextField(null=True)),
                ('target_mandatory', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(choices=[('PAID', 'PAID'), ('PARTIAL', 'PARTIAL'), ('PENDING', 'PENDING')], default='PENDING', max_length=100)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH'), ('UPI', 'UPI'), ('NETBANKING', 'NETBANKING')], default='CASH', max_length=100)),
                ('testimonial', models.TextField(null=True)),
                ('current_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salary_date', models.DateField(blank=True, null=True)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('adv_payment_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffIncentives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('incentives', models.ManyToManyField(to='accounts.incentives')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsentiveSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(choices=[('PAID', 'PAID'), ('PARTIAL', 'PARTIAL'), ('PENDING', 'PENDING')], default='PENDING', max_length=100)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH'), ('UPI', 'UPI'), ('NETBANKING', 'NETBANKING')], default='CASH', max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('testimonial', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('staff_incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffincentives')),
            ],
        ),
    ]
