# Generated by Django 4.1.5 on 2023-07-19 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_incentives_staffsalary_staffincentives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentives',
            name='target',
        ),
        migrations.AddField(
            model_name='staffincentives',
            name='achieved_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='staffincentives',
            name='incentive_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staffincentives',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='staffincentives',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffincentives',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('UPI', 'UPI'), ('NETBANKING', 'NETBANKING')], default='CASH', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffincentives',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('PARTIAL', 'PARTIAL'), ('PENDING', 'PENDING')], default='PENDING', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffincentives',
            name='target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='staffincentives',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='salary_message',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='staffincentives',
            name='incentives',
        ),
        migrations.DeleteModel(
            name='InsentiveSalary',
        ),
        migrations.AddField(
            model_name='staffincentives',
            name='incentives',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.incentives'),
        ),
    ]
