# Generated by Django 4.1.5 on 2023-07-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_remove_incentives_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentives',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='staffincentives',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='staffsalary',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
