# Generated by Django 4.1.5 on 2023-08-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_materialreference_vstatus'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='materialreference',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('user', 'topic'), name='unique_faculty_topic_material'),
        ),
        migrations.AddConstraint(
            model_name='materialreference',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('user', 'module'), name='unique_faculty_modul_material'),
        ),
        migrations.AddConstraint(
            model_name='materialreference',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', True), _negated=True), fields=('user', 'subtopic'), name='unique_faculty_subtopic_material'),
        ),
    ]
