# Generated by Django 4.1.5 on 2023-08-03 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_materialreference_unique_faculty_topic_material_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='materialreference',
            name='unique_faculty_topic_material',
        ),
        migrations.RemoveConstraint(
            model_name='materialreference',
            name='unique_faculty_modul_material',
        ),
        migrations.RemoveConstraint(
            model_name='materialreference',
            name='unique_faculty_subtopic_material',
        ),
    ]
