# Generated by Django 4.1.5 on 2023-08-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_remove_materialreference_unique_faculty_topic_material_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='materialreference',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('category__isnull', False), ('level__isnull', True), ('course__isnull', True), ('module__isnull', True), ('subject__isnull', True), ('topic__isnull', True), ('subtopic__isnull', True)), models.Q(('category__isnull', True), ('level__isnull', False), ('course__isnull', True), ('module__isnull', True), ('subject__isnull', True), ('topic__isnull', True), ('subtopic__isnull', True)), models.Q(('category__isnull', True), ('level__isnull', True), ('course__isnull', False), ('module__isnull', True), ('subject__isnull', True), ('topic__isnull', True), ('subtopic__isnull', True)), models.Q(('category__isnull', True), ('level__isnull', True), ('course__isnull', True), ('module__isnull', False), ('subject__isnull', True), ('topic__isnull', True), ('subtopic__isnull', True)), models.Q(('category__isnull', True), ('level__isnull', True), ('course__isnull', True), ('module__isnull', True), ('subject__isnull', False), ('topic__isnull', True), ('subtopic__isnull', True)), models.Q(('category__isnull', True), ('level__isnull', True), ('course__isnull', True), ('module__isnull', True), ('subject__isnull', True), ('topic__isnull', False), ('subtopic__isnull', True)), models.Q(('category__isnull', True), ('level__isnull', True), ('course__isnull', True), ('module__isnull', True), ('subject__isnull', True), ('topic__isnull', True), ('subtopic__isnull', False)), _connector='OR'), name='only_one_field_non_null_constraint'),
        ),
    ]
