# Generated by Django 4.1.5 on 2023-08-09 04:39

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_materialreference_only_one_field_non_null_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialreference',
            name='vstatus',
        ),
        migrations.AddField(
            model_name='materialuploads',
            name='edited_on',
            field=models.CharField(choices=[('SET', 'SET'), ('TYPE', 'TYPE')], default='TYPED', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materialuploads',
            name='edited_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialuploads',
            name='updated_file',
            field=models.FileField(null=True, storage=accounts.models.S3Storage(), upload_to='materials/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx', 'docx', 'plg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='materialuploads',
            name='vstatus_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialuploads',
            name='vstatus_research',
            field=models.BooleanField(default=False),
        ),
    ]
