# Generated by Django 4.1.5 on 2023-08-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_remove_materialreference_vstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialuploads',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='materialuploads',
            name='edited_on',
            field=models.CharField(choices=[('SET', 'SET'), ('TYPE', 'TYPE')], default='TYPE', max_length=100, null=True),
        ),
    ]
