# Generated by Django 4.1.5 on 2023-08-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_materialuploads_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialuploads',
            name='reject_updated_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialuploads',
            name='reject_updated_file_reason',
            field=models.TextField(null=True),
        ),
    ]
