# Generated by Django 4.1.5 on 2023-08-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_materialuploads_reject_updated_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_account',
            field=models.BooleanField(default=False),
        ),
    ]
