# Generated by Django 4.1.5 on 2023-08-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_studiovideo_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialuploads',
            name='reject_updated_file_fac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialuploads',
            name='reject_updated_file_reason_fac',
            field=models.TextField(null=True),
        ),
    ]
