# Generated by Django 4.1.5 on 2023-08-31 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_materialuploads_reject_updated_file_fac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffincentives',
            name='achieved_target',
        ),
        migrations.RemoveField(
            model_name='staffincentives',
            name='incentive_message',
        ),
        migrations.RemoveField(
            model_name='staffincentives',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='staffincentives',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='staffincentives',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='staffincentives',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='staffincentives',
            name='updated',
        ),
        migrations.CreateModel(
            name='StaffIncentiveAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('achieved_target', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('PAID', 'PAID'), ('PARTIAL', 'PARTIAL'), ('PENDING', 'PENDING')], default='PENDING', max_length=100, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH'), ('UPI', 'UPI'), ('NETBANKING', 'NETBANKING')], default='CASH', max_length=100, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('incentive_message', models.TextField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('staffincetive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.staffincentives')),
            ],
        ),
    ]
