# Generated by Django 4.1.5 on 2023-09-02 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_remove_staffincentives_achieved_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newquestionpool',
            name='add_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffincentiveamount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
