# Generated by Django 4.1.5 on 2023-09-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_newquestionpool_add_user_staffincentiveamount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiovideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
