# Generated by Django 4.1.5 on 2023-09-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_historicalfacultycourseaddition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfaculty',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
