# Generated by Django 4.1.5 on 2023-09-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_questionpaper_banner_questionpaper_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
