from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(QuizPool)
admin.site.register(DailyNews)
admin.site.register(StudyMaterial)
admin.site.register(Shorts)
admin.site.register(ShortsWatched)
admin.site.register(MobileBanner)
admin.site.register(QuizPoolAnswers)
admin.site.register(QuizPoolUserRoom)
admin.site.register(BooksType)
admin.site.register(Books)
admin.site.register(BatchPackages)
admin.site.register(GeneralVideos)
admin.site.register(GeneralVideosCategory)
admin.site.register(SuccessStories)
admin.site.register(LibraryUser)
admin.site.register(BookLend)
admin.site.register(Stories)
admin.site.register(StoriesCategory)
admin.site.register(StoriesWatched)
admin.site.register(PackageMaterials)
admin.site.register(VedioMeterialAndQuestions)
admin.site.register(VedioPackage)
admin.site.register(CurrentAffairsQuestions)
admin.site.register(CurrentAffairsVideos)
admin.site.register(Comments)
admin.site.register(ExampaperPackage)
admin.site.register(DailyExams)
admin.site.register(SpecialExams)
admin.site.register(PopularFaculty)
admin.site.register(CartItems)
admin.site.register(ScholarshipType)
admin.site.register(ScholarshipApproval)
admin.site.register(PollFightQuestion)
admin.site.register(QuestionBook)
admin.site.register(QuestionCategory)
admin.site.register(Groups)
# admin.site.register(scholarship-approval)
admin.site.register(StudentFeeCollection)
# admin.site.register(QuestionCategory)
admin.site.register(PurchaseDetails)
admin.site.register(Views)
admin.site.register(Likes)
admin.site.register(QuestionpaperAttend)
# admin.site.register(Books)
admin.site.register(LibraryFine)
admin.site.register(PackageQuizPoolUserRoom)
admin.site.register(PackageQuizPoolAnswers)
admin.site.register(OnlineCoursePackage)
admin.site.register(NoticeBoard)
admin.site.register(VideoClassesBatch)
admin.site.register(ZoomMeetings)
admin.site.register(ReportFlag)



