# Generated by Django 4.1.5 on 2023-05-22 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_is_active_student_admission_enquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 5, 22, 13, 39, 3, 609423, tzinfo=datetime.timezone.utc)),
        ),
    ]
