# Generated by Django 4.1.5 on 2023-06-06 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_alter_timetable_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0005_feepayment_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('isverified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAffairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('file', models.FileField(upload_to='')),
                ('video', models.CharField(choices=[('V', 'VIMEO'), ('Y', 'YOUTUBE')], default='V', max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('publish_on', models.DateField(null=True)),
                ('course', models.ManyToManyField(to='course.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
