# Generated by Django 4.1.5 on 2023-06-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentotp_currentaffairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emailverified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='currentaffairs',
            name='video',
            field=models.CharField(choices=[('V', 'VIMEO'), ('Y', 'YOUTUBE')], default='V', max_length=200, null=True),
        ),
    ]
