# Generated by Django 4.1.5 on 2023-06-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_version_studentotp_user_alter_student_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
