# Generated by Django 4.1.5 on 2023-06-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_facultyattendence_salary_date'),
        ('student', '0009_alter_version_name_alter_version_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=255)),
                ('icon', models.ImageField(null=True, upload_to='')),
                ('book_price', models.CharField(max_length=5)),
                ('discount_price', models.CharField(max_length=5, null=True)),
                ('no_of_pages', models.IntegerField(null=True)),
                ('edition', models.CharField(max_length=100, null=True)),
                ('publish_on', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ManyToManyField(to='course.course')),
            ],
        ),
    ]
