# Generated by Django 4.1.5 on 2023-06-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_student_is_delete_student_selected_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentaffairs',
            name='videolength',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='currentaffairs',
            name='vimeoid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='currentaffairs',
            name='vname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
