# Generated by Django 4.1.5 on 2023-06-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_currentaffairs_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaffairs',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
