# Generated by Django 4.1.5 on 2023-06-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_currentaffairs_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentaffairs',
            name='course',
        ),
        migrations.AddField(
            model_name='currentaffairs',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='currentaffairs',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
