# Generated by Django 4.1.5 on 2023-07-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_remove_currentaffairs_course_currentaffairs_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
