# Generated by Django 4.1.5 on 2023-07-04 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0042_batch_installment_count'),
        ('student', '0017_publications_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplicationOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('marital_status', models.CharField(choices=[('1', 'Single'), ('2', 'Married')], max_length=1, null=True)),
                ('religion', models.CharField(max_length=255, null=True)),
                ('caste', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('qualification', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.branch')),
            ],
        ),
    ]
