# Generated by Django 4.1.5 on 2023-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_studentapplicationoffline'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplicationoffline',
            name='phone',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
