# Generated by Django 4.1.5 on 2023-07-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_studentapplicationoffline_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplicationoffline',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
