# Generated by Django 4.1.5 on 2023-07-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_studentapplicationoffline_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publications',
            name='medium',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='order_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='paperback',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
