# Generated by Django 4.1.5 on 2023-07-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_publications_is_online_publications_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='admission_time_price',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='old_student',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='outsider',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
