# Generated by Django 4.1.5 on 2023-07-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_publications_admission_time_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='admission_time_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='publications',
            name='book_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='publications',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='publications',
            name='old_student',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='publications',
            name='outsider',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
