# Generated by Django 4.1.5 on 2023-07-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_alter_publications_admission_time_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='offlinebook_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
