# Generated by Django 4.1.5 on 2023-07-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_publications_offlinebook_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentaffairs',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
