# Generated by Django 4.1.5 on 2023-08-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scholarship',
            field=models.BooleanField(default=False),
        ),
    ]
