# Generated by Django 4.1.5 on 2023-08-23 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_studentapplicationoffline_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('declaration', models.TextField()),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
