# Generated by Django 4.1.5 on 2023-09-21 08:42

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_alter_currentaffairs_icon_alter_publications_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaffairs',
            name='icon',
            field=models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='dev-aceapp-public', default_acl='public-read', querystring_auth=False), upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='icon',
            field=models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='dev-aceapp-public', default_acl='public-read', querystring_auth=False), upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='dev-aceapp-public', default_acl='public-read', querystring_auth=False), upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='studentapplicationoffline',
            name='photo',
            field=models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='dev-aceapp-public', default_acl='public-read', querystring_auth=False), upload_to='Images/'),
        ),
    ]
